#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'
{% if cookiecutter.use_neo4j == 'y' %}
# Wait for the bundled neo4j service, unless Django is pointed at another server.
# The first start takes longer: Neo4j sets the password and installs plugins.
if [ -z "${DJANGO_NEO4J_URI:-}" ]; then
    wait-for-it "neo4j:7687" -t 120

    >&2 echo 'Neo4j is available'
fi
{% endif %}
exec "$@"
