#!/bin/sh

### Upload the /backups folder to Amazon S3
###
### Usage:
###     $ docker compose -f docker-compose.production.yml run --rm awscli upload

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

export AWS_ACCESS_KEY_ID="${DJANGO_AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${DJANGO_AWS_SECRET_ACCESS_KEY}"
export AWS_STORAGE_BUCKET_NAME="${DJANGO_AWS_STORAGE_BUCKET_NAME}"


message_info "Upload the backups directory to S3 bucket {$AWS_STORAGE_BUCKET_NAME}"

aws s3 cp ${BACKUP_DIR_PATH} s3://${AWS_STORAGE_BUCKET_NAME}${BACKUP_DIR_PATH} --recursive

message_info "Cleaning the directory ${BACKUP_DIR_PATH}"

{% if cookiecutter.use_neo4j == 'y' -%}
# /backups/neo4j is the Neo4j backups volume, mounted inside this one: delete
# the files but keep the directories, since a mount point can't be removed.
find ${BACKUP_DIR_PATH} -type f -delete
{% else -%}
rm -rf ${BACKUP_DIR_PATH}/*
{% endif %}
message_success "Finished uploading and cleaning."
