#!/usr/bin/env bash


### Restore a database from a backup, replacing its current contents.
###
### Neo4j must be stopped while the restore runs.
###
### Parameters:
###     <1> filename of an existing backup.
###     <2> name of the database to restore into (default: neo4j).
###
### Usage:
###     $ docker compose -f <environment>.yml stop neo4j
###     $ docker compose -f <environment>.yml run --rm neo4j restore <1>
###     $ docker compose -f <environment>.yml start neo4j


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


if [[ -z ${1+x} ]]; then
    message_error "Backup filename is not specified yet it is a required parameter. Make sure you provide one and try again."
    exit 1
fi
backup_filename="${BACKUP_DIR_PATH}/${1}"
if [[ ! -f "${backup_filename}" ]]; then
    message_error "No backup with the specified filename found. Check out the 'backups' maintenance script output to see if there is one and try again."
    exit 1
fi
database="${2:-neo4j}"

message_welcome "Restoring the '${database}' database from the '${backup_filename}' backup..."

if ! neo4j-admin database load "${database}" --from-stdin --overwrite-destination=true < "${backup_filename}"; then
    message_error "The restore failed. If Neo4j is still running, stop it first ('docker compose -f <environment>.yml stop neo4j') and try again."
    exit 1
fi

message_success "The '${database}' database has been restored from the '${backup_filename}' backup."
